return {
   -- PLAYER
   PLAYER_SIZE = 16,
   PLAYER_START_TEST_LEVEL = {x = 32, y = 32},
   -- PLAYER MOVE CONF
   PLAYER_MAX_SPEED = 300,
   PLAYER_FORCE = 8000,
   PLAYER_LOOKAHEAD = 75,

   -- TEST GUN CONF
   TEST_GUN_COOLDOWN = 0,
   TEST_GUN_PROJECTILE_SPEED = 2000
}
